dependencies:
  - uniswap/v3-periphery@1.0.0
  - uniswap/v3-core@1.0.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0

compiler:
  solc:
    remappings:
      - "@uniswap/v3-periphery=uniswap/v3-periphery@1.0.0"
      - "@uniswap/v3-core=uniswap/v3-core@1.0.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
autofetch_sources: True
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: development
  mainnet-fork:
    dai: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    uniswap_router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    router_fees: 3000
  kovan:
    dai: "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
    weth: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    uniswap_router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    router_fees: 3000
wallets:
  from_key: ${PRIVATE_KEY}
