version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: pfontain/cci-dca-browie:0.0.2
        auth:
          username: pfontain
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: pfontain/cci-dca-browie:0.0.2
        auth:
          username: pfontain
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: export WEB3_INFURA_PROJECT_ID=$WEB3_INFURA_PROJECT_ID && brownie test --network mainnet-fork

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
